/* eslint-disable prettier/prettier */
import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();

function getCars() {
  return [
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'toyota',
      model: 'corolla',
      category: 'standard',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 38,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e51',
      brand: 'opel',
      model: 'astra',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 35,
      airCon: false,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e52',
      brand: 'toyota',
      model: 'aygo',
      category: 'mini',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 4,
      price: 33,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e53',
      brand: 'toyota',
      model: 'yaris',
      category: 'compact',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 31,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e54',
      brand: 'renault',
      model: 'clio',
      category: 'eco',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 4,
      price: 29,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e55',
      brand: 'volkswagen',
      model: 'polo',
      category: 'eco',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 24,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e57',
      brand: 'skoda',
      model: 'fabia',
      category: 'eco',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 35,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e58',
      brand: 'volkswagen',
      model: 'tiguan',
      category: 'standard',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 40,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e59',
      brand: 'opel',
      model: 'corsa',
      category: 'eco',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 33,
      airCon: false,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e50',
      brand: 'mercedes',
      model: 'a-class',
      category: 'premium',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 60,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e16',
      brand: 'volkswagen',
      model: 'arteon',
      category: 'premium',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 4,
      price: 33,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e26',
      brand: 'bmw',
      model: 'series-3',
      category: 'premium',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 37,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e36',
      brand: 'mercedes',
      model: 'glc',
      category: 'premium',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 72,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e46',
      brand: 'audi',
      model: 'a4',
      category: 'premium',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 83,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e66',
      brand: 'renault',
      model: 'megane',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 24,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e76',
      brand: 'volkswagen',
      model: 'golf',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 23,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e86',
      brand: 'skoda',
      model: 'rapid',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 31,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e96',
      brand: 'skoda',
      model: 'scala',
      category: 'compact',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 30,
      airCon: true,
    },
    {
      id: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e06',
      brand: 'volkswagen',
      model: 'troc',
      category: 'compact',
      gearbox: 'automatic',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 36,
      airCon: true,
    },
    {
      id: 'c920c7b1-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'honda',
      model: 'civic',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 28,
      airCon: true,
    },
    {
      id: 'c920c7b2-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'honda',
      model: 'jazz',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 22,
      airCon: true,
    },
    {
      id: 'c920c7b3-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'honda',
      model: 'fit',
      category: 'mini',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 20,
      airCon: true,
    },
    {
      id: 'c920c7b4-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'audi',
      model: 'a3-sportback',
      category: 'compact',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 43,
      airCon: true,
    },
    {
      id: 'c920c7b5-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'volkswagen',
      model: 'passat',
      category: 'standard',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 35,
      airCon: true,
    },
    {
      id: 'c920c7b6-a67d-4edb-8ce7-e3c9f3889e56',
      brand: 'skoda',
      model: 'octavia',
      category: 'standard',
      gearbox: 'manual',
      description: 'Lorem ipsum dolor sit amet, bibendum sit amet eu diam.',
      seats: 5,
      price: 35,
      airCon: true,
    },
  ];
}

function getOrders() {
  return [
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17260',
      firstName: 'asdfasdfasd',
      lastName: 'sdafasdf',
      message: 'fasdfasdfasd',
      phone: 516435786,
      street: 'fasdfasdf',
      totalCost: 190,
      carId: 'c920c7b9-a67d-4edb-8ce7-e3c9f3889e56',
    },
  ];
}

async function seed() {
  await Promise.all(
    getCars().map((car) => {
      return db.car.create({ data: car });
    }),
  );

  await Promise.all(
    getOrders().map(({ carId, ...orderData }) => {
      return db.order.create({
        data: {
          ...orderData,
          order: {
            connect: { id: carId },
          },
        },
      });
    }),
  );
}

seed();
