const initialState = {
  categories: [
    { id: 'all', name: 'All' },
    { id: 'standard', name: 'Standard' },
    { id: 'compact', name: 'Compact' },
    { id: 'mini', name: 'Mini' },
    { id: 'eco', name: 'Eco' },
    { id: 'premium', name: 'Premium' },
  ],
  brands: [
    { id: 'mercedes', name: 'Mercedes' },
    { id: 'skoda', name: 'Skoda' },
    { id: 'bmw', name: 'BMW' },
    { id: 'opel', name: 'Opel' },
    { id: 'honda', name: 'Honda' },
    { id: 'audi', name: 'Audi' },
    { id: 'toyota', name: 'Toyota' },
    { id: 'renault', name: 'Renault' },
    { id: 'volkswagen', name: 'Volkswagen' },
  ],
  cars: [
    {
      id: 'toyota-corolla',
      brand: 'toyota',
      model: 'corolla',
      category: 'standard',
      gearbox: 'automatic',
      seats: 5,
      price: 38,
      airCon: true,
    },
    {
      id: 'opel-astra',
      brand: 'opel',
      model: 'astra',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 35,
      airCon: false,
    },
    {
      id: 'toyota-aygo',
      brand: 'toyota',
      model: 'aygo',
      category: 'mini',
      gearbox: 'manual',
      seats: 4,
      price: 33,
      airCon: true,
    },
    {
      id: 'toyota-yaris',
      brand: 'toyota',
      model: 'yaris',
      category: 'compact',
      gearbox: 'automatic',
      seats: 5,
      price: 31,
      airCon: true,
    },
    {
      id: 'renault-clio',
      brand: 'renault',
      model: 'clio',
      category: 'eco',
      gearbox: 'manual',
      seats: 4,
      price: 29,
      airCon: true,
    },
    {
      id: 'volkswagen-polo',
      brand: 'volkswagen',
      model: 'polo',
      category: 'eco',
      gearbox: 'manual',
      seats: 5,
      price: 24,
      airCon: true,
    },
    {
      id: 'skoda-fabia',
      brand: 'skoda',
      model: 'fabia',
      category: 'eco',
      gearbox: 'manual',
      seats: 5,
      price: 35,
      airCon: true,
    },
    {
      id: 'volkswagen-tiguan',
      brand: 'volkswagen',
      model: 'tiguan',
      category: 'standard',
      gearbox: 'manual',
      seats: 5,
      price: 40,
      airCon: true,
    },
    {
      id: 'opel-corsa',
      brand: 'opel',
      model: 'corsa',
      category: 'eco',
      gearbox: 'manual',
      seats: 5,
      price: 33,
      airCon: false,
    },
    {
      id: 'mercedes-a-class',
      brand: 'mercedes',
      model: 'a-class',
      category: 'premium',
      gearbox: 'automatic',
      seats: 5,
      price: 60,
      airCon: true,
    },
    {
      id: 'volkswagen-arteon',
      brand: 'volkswagen',
      model: 'arteon',
      category: 'premium',
      gearbox: 'automatic',
      seats: 4,
      price: 33,
      airCon: true,
    },
    {
      id: 'bmw-series-3',
      brand: 'bmw',
      model: 'series-3',
      category: 'premium',
      gearbox: 'automatic',
      seats: 5,
      price: 37,
      airCon: true,
    },
    {
      id: 'mercedes-glc',
      brand: 'mercedes',
      model: 'glc',
      category: 'premium',
      gearbox: 'automatic',
      seats: 5,
      price: 72,
      airCon: true,
    },
    {
      id: 'audi-a4',
      brand: 'audi',
      model: 'a4',
      category: 'premium',
      gearbox: 'automatic',
      seats: 5,
      price: 83,
      airCon: true,
    },
    {
      id: 'renault-megane',
      brand: 'renault',
      model: 'megane',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 24,
      airCon: true,
    },
    {
      id: 'volkswagen-golf',
      brand: 'volkswagen',
      model: 'golf',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 23,
      airCon: true,
    },
    {
      id: 'skoda-rapid',
      brand: 'skoda',
      model: 'rapid',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 31,
      airCon: true,
    },
    {
      id: 'skoda-scala',
      brand: 'skoda',
      model: 'scala',
      category: 'compact',
      gearbox: 'automatic',
      seats: 5,
      price: 30,
      airCon: true,
    },
    {
      id: 'volkswagen-troc',
      brand: 'volkswagen',
      model: 'troc',
      category: 'compact',
      gearbox: 'automatic',
      seats: 5,
      price: 36,
      airCon: true,
    },
    {
      id: 'honda-civic',
      brand: 'honda',
      model: 'civic',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 28,
      airCon: true,
    },
    {
      id: 'honda-jazz',
      brand: 'honda',
      model: 'jazz',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 22,
      airCon: true,
    },
    {
      id: 'honda-fit',
      brand: 'honda',
      model: 'fit',
      category: 'mini',
      gearbox: 'manual',
      seats: 5,
      price: 20,
      airCon: true,
    },
    {
      id: 'audi-a3-sportback',
      brand: 'audi',
      model: 'a3-sportback',
      category: 'compact',
      gearbox: 'manual',
      seats: 5,
      price: 43,
      airCon: true,
    },
    {
      id: 'volkswagen-passat',
      brand: 'volkswagen',
      model: 'passat',
      category: 'standard',
      gearbox: 'manual',
      seats: 5,
      price: 35,
      airCon: true,
    },
    {
      id: 'skoda-octavia',
      brand: 'skoda',
      model: 'octavia',
      category: 'standard',
      gearbox: 'manual',
      seats: 5,
      price: 35,
      airCon: true,
    },
  ],
  cart: {
    products: [],
  },
  orders: {},
};

export default initialState;
